// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PaymentProcessingQueueApi.Infrastructure.Persistence;

#nullable disable

namespace PaymentProcessingQueueApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PaymentProcessingQueueApi.Domain.Entities.Transaction", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<bool>("Active")
                    .HasColumnType("boolean");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<string>("ClientType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Cpf")
                    .IsRequired()
                    .HasMaxLength(14)
                    .HasColumnType("character varying(14)");

                b.Property<DateTime>("CutoffTime")
                    .HasColumnType("timestamp without time zone");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("FraudRisk")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<int>("Priority")
                    .HasColumnType("integer");

                b.Property<string>("Reference")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("character varying(30)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp without time zone");

                b.HasKey("Id");

                b.HasIndex("Active");

                b.HasIndex("Cpf");

                b.HasIndex("Status");

                b.ToTable("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
